version: 0.0
os: linux
files:
  - source: files
    destination: /etc/rcon
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install_connect.sh
      timeout: 3000
      runas: root
  AfterInstall:
    - location: /activate_connect.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /stop_service.sh
      timeout: 300
      runas: root
