version: 0.0
os: linux
files:
        - source: /files
          destination: /etc/shinyproxy
hooks:
        ApplicationStop:
                - location: /stop_service.sh
                  timeout: 300
                  runas: root
        BeforeInstall:
                - location: /install_dependencies.sh
                  timeout: 900
                  runas: root
        AfterInstall:
                - location: /configure_application.sh
                  timeout: 300
                  runas: root
        ApplicationStart:
                - location: /start_service.sh
                  timeout: 300
                  runas: root
